sylius_fixtures:
    suites:
        default:
            fixtures:
                inchoo_product:
                  options:
                       amount: 100
        inchoo:
            fixtures:
                inchoo_product:
                  options:
                       amount: 100

